FROM nginx:latest
LABEL maintainer 'Deyvisson Eduardo <deyvissoneduardo22@gmail.com>'



#Copiando arquivos local para vm
RUN echo '<h1>Sem conteudo</h1>' > /usr/share/nginx/html/conteudo.html
COPY *.html /usr/share/nginx/html/

