version: '3'

services: 
    web:
        image: nginx
        volumes: 
            - ./nginx/app.conf:/etc/nginx/nginx.conf
        depends_on: 
            - minha_app    
        ports: 
            - 8080:80
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: admin
        ports: 
            - "5432"
        volumes: 
            - ./dados_postgres:/var/lib/postgresql/data
    minha_app:
        image: deyvissoneduardo/minha-app-dockerizada:latest
        build: ./image
        depends_on:
        - db                 